### ISSUE TITLE
Readme 

### ISSUE THREAD

**Issue by gopeine** [ccev/Discordopole#15]
Command issue: you wrote !boards create... on all commands in readme for raids / eggs... it is just !board.... and you could write !board create stats area ...
![17E87DAC-0A37-4742-BB44-ED5E8B4F0685](https://user-images.githubusercontent.com/47991578/82097421-29311500-9703-11ea-9a21-da28ddac5b0a.png)

**Comment by idna-ved** [comment]
ups. fixed. thanks
