### ISSUE TITLE
Second table for Shinys, request

### ISSUE THREAD

**Issue by gopeine** [ccev/Discordopole#28]
Second table for mons is good and second table for Shiny would be also realy good... shiny table for MAD is trs_stats_detect_raw and it is big as hell, so it need a truncate from time to time with loss of all... so a second table would be realy usefull if discordopole could read out and use it... simple: shiny; named table. mysql command for transfer (MAD tested): insert into shiny select * from trs_stats_detect_raw on duplicate key update shiny.id=trs_stats_detect_raw.id,shiny.worker=trs_stats_detect_raw.worker,
shiny.type_id=trs_stats_detect_raw.type_id,shiny.type=trs_stats_detect_raw.type,
shiny.count=trs_stats_detect_raw.count,shiny.is_shiny=trs_stats_detect_raw.is_shiny,
shiny.timestamp_scan=trs_stats_detect_raw.timestamp_scan;  

Integration realy apreciated.

**Comment by idna-ved** [comment]
added an option in config.ini for alt shiny table. needs testing

**Comment by gopeine** [comment]
Wow thx that was fast. truncated original trs_stats_detect_raw so it only used the new shiny table and it lookes like that it works well. issue can be closed
