### ISSUE TITLE
Raid Board Title 

### ISSUE THREAD

**Issue by marcb1387** [ccev/Discordopole#3]
i wanted to see if we could add the level number to the raid boards title to be helpful if you have a separate board for each level.

**Comment by kamieniarz** [comment]
Actually board names could be predefined by us eg `!board create egg london 3 Raid Eggs London level 3` where `Raid Eggs London level 3` is the name

**Comment by ccev** [comment]
Discordopole will now always default to the title it had before but the title can be changed in config/boards.json
